name: Build and test
on: [push]

concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm i

      - name: Test project
        run: npm test